/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public boolean someLibraryMethod() {
		return true;
	}

	public static void main(String[] args) {
		System.out.println("Hello");

		//System.getProperties().list(System.out);

		System.out.println(System.getProperty("sun.arch.data.model"));

		System.out.println(System.getProperty("os.name"));
		
	}
}
